{
  "uid" : "3837fe101c128ff7",
  "name" : "test__delete_article",
  "fullName" : "test.conduit_panniangyan_test.TestConduit#test__delete_article",
  "historyId" : "8347a4ef5ed259c96d8e056b7cf5ab81",
  "time" : {
    "start" : 1627899646813,
    "stop" : 1627899646813,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "TypeError: setup() takes 0 positional arguments but 1 was given",
  "statusTrace" : "cls = <class '_pytest.runner.CallInfo'>\nfunc = <function call_runtest_hook.<locals>.<lambda> at 0x7f09d2ec1ca0>\nwhen = 'setup'\nreraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: \"Callable[[], TResult]\",\n        when: \"Literal['collect', 'setup', 'call', 'teardown']\",\n        reraise: Optional[\n            Union[Type[BaseException], Tuple[Type[BaseException], ...]]\n        ] = None,\n    ) -> \"CallInfo[TResult]\":\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: Optional[TResult] = func()\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:311: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>\n    lambda: ihook(item=item, **kwds), when=when, reraise=reraise\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>\n    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:13: in pytest_runtest_setup\n    call_optional(item.parent.obj, \"setup\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nobj = <conduit_panniangyan_test.TestConduit object at 0x7f09d2e66ac0>\nname = 'setup'\n\n    def call_optional(obj, name):\n        method = getattr(obj, name, None)\n        isfixture = hasattr(method, \"_pytestfixturefunction\")\n        if method is not None and not isfixture and callable(method):\n            # If there's any problems allow the exception to raise rather than\n            # silently ignoring them.\n>           method()\nE           TypeError: setup() takes 0 positional arguments but 1 was given\n\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/nose.py:38: TypeError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "conduit_panniangyan_test"
  }, {
    "name" : "subSuite",
    "value" : "TestConduit"
  }, {
    "name" : "host",
    "value" : "fv-az39-326"
  }, {
    "name" : "thread",
    "value" : "3652-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.conduit_panniangyan_test"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 17,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 17
      },
      "items" : [ {
        "uid" : "8408cfa053c047f7",
        "reportUrl" : "https://panniangyan.github.io/conduit/19//#testresult/8408cfa053c047f7",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627899220956,
          "stop" : 1627899220956,
          "duration" : 0
        }
      }, {
        "uid" : "e639a9e48d34bd30",
        "reportUrl" : "https://panniangyan.github.io/conduit/18//#testresult/e639a9e48d34bd30",
        "status" : "broken",
        "statusDetails" : "TypeError: setup() takes 0 positional arguments but 1 was given",
        "time" : {
          "start" : 1627898435534,
          "stop" : 1627898435534,
          "duration" : 0
        }
      }, {
        "uid" : "d2a84af3ae89ba4b",
        "reportUrl" : "https://panniangyan.github.io/conduit/17//#testresult/d2a84af3ae89ba4b",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=52653): Max retries exceeded with url: /session/f04a3cdd168c74da301d0c38b9cb3db9/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fca1c170ca0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627896379895,
          "stop" : 1627896379895,
          "duration" : 0
        }
      }, {
        "uid" : "9763af6d0f56b9fe",
        "reportUrl" : "https://panniangyan.github.io/conduit/16//#testresult/9763af6d0f56b9fe",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=60017): Max retries exceeded with url: /session/b1a5c94c7bc7022ef76dd2ebb8ba0f70/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1a75062250>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627895213594,
          "stop" : 1627895213594,
          "duration" : 0
        }
      }, {
        "uid" : "a43b3afa1be26198",
        "reportUrl" : "https://panniangyan.github.io/conduit/15//#testresult/a43b3afa1be26198",
        "status" : "broken",
        "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=43719): Max retries exceeded with url: /session/91742e4ead70df7aa6cbcad06f4f1bd2/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe18cfd50a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
        "time" : {
          "start" : 1627892997039,
          "stop" : 1627892997039,
          "duration" : 0
        }
      }, {
        "uid" : "2b2a8a28cedf7b8d",
        "reportUrl" : "https://panniangyan.github.io/conduit/14//#testresult/2b2a8a28cedf7b8d",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'WebDriver' object has no attribute 'webdriver'",
        "time" : {
          "start" : 1627892617400,
          "stop" : 1627892617400,
          "duration" : 0
        }
      }, {
        "uid" : "e592222212cdad6a",
        "reportUrl" : "https://panniangyan.github.io/conduit/12//#testresult/e592222212cdad6a",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627888455667,
          "stop" : 1627888455667,
          "duration" : 0
        }
      }, {
        "uid" : "48f7187ef91e60e3",
        "reportUrl" : "https://panniangyan.github.io/conduit/11//#testresult/48f7187ef91e60e3",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829932601,
          "stop" : 1627829932601,
          "duration" : 0
        }
      }, {
        "uid" : "a9e92dc252b48f20",
        "reportUrl" : "https://panniangyan.github.io/conduit/10//#testresult/a9e92dc252b48f20",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829830086,
          "stop" : 1627829830086,
          "duration" : 0
        }
      }, {
        "uid" : "fdb40f43aea2006b",
        "reportUrl" : "https://panniangyan.github.io/conduit/9//#testresult/fdb40f43aea2006b",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627829050019,
          "stop" : 1627829050019,
          "duration" : 0
        }
      }, {
        "uid" : "a4139a033d12da0f",
        "reportUrl" : "https://panniangyan.github.io/conduit/8//#testresult/a4139a033d12da0f",
        "status" : "broken",
        "statusDetails" : "AttributeError: 'TestConduit' object has no attribute 'browser'",
        "time" : {
          "start" : 1627828717765,
          "stop" : 1627828717765,
          "duration" : 0
        }
      }, {
        "uid" : "e5bdb99c842572de",
        "reportUrl" : "https://panniangyan.github.io/conduit/7//#testresult/e5bdb99c842572de",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627828259736,
          "stop" : 1627828259736,
          "duration" : 0
        }
      }, {
        "uid" : "ad0b83656f45c04d",
        "reportUrl" : "https://panniangyan.github.io/conduit/6//#testresult/ad0b83656f45c04d",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627827072913,
          "stop" : 1627827072913,
          "duration" : 0
        }
      }, {
        "uid" : "36b5dcf00f82f12c",
        "reportUrl" : "https://panniangyan.github.io/conduit/5//#testresult/36b5dcf00f82f12c",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627819959948,
          "stop" : 1627819959948,
          "duration" : 0
        }
      }, {
        "uid" : "eb44837ac7c3bec0",
        "reportUrl" : "https://panniangyan.github.io/conduit/4//#testresult/eb44837ac7c3bec0",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818415258,
          "stop" : 1627818415258,
          "duration" : 0
        }
      }, {
        "uid" : "620b9b745332aea6",
        "reportUrl" : "https://panniangyan.github.io/conduit/3//#testresult/620b9b745332aea6",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "time" : {
          "start" : 1627818164873,
          "stop" : 1627818164873,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "3837fe101c128ff7.json",
  "parameterValues" : [ ]
}