{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=48927): Max retries exceeded with url: /session/355ad5e691226a1a1d21f2fb1adf08b5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4fc92efd0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "test__registration",
        "uid" : "83e6d251a5b6b20d",
        "parentUid" : "425eeef620e4b4b9dc3f13ca814a55d0",
        "status" : "broken",
        "time" : {
          "start" : 1627900174199,
          "stop" : 1627900174199,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "425eeef620e4b4b9dc3f13ca814a55d0"
    }, {
      "name" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=48927): Max retries exceeded with url: /session/355ad5e691226a1a1d21f2fb1adf08b5/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fc4fc0343d0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
      "children" : [ {
        "name" : "test__login",
        "uid" : "4b436dad5eb26d7d",
        "parentUid" : "717f38ea0de8cf7e621b0ed5ea682cfe",
        "status" : "broken",
        "time" : {
          "start" : 1627900174424,
          "stop" : 1627900174424,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "717f38ea0de8cf7e621b0ed5ea682cfe"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ],
  "name" : "categories"
}